language: csharp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "L8zr1nS7zVhSEjJrLwXiwAyi7k6hm3yCZEm6OX9N3HePZwieOT2964yZxpqXzVWn0k/8blpvksZ5jpsXSLID+xBkWAF3rDbCKXpNcDOHIs06Q9JnwrQkXM97y0nLFWUF76e8u17JYNVUHfw+oy8DfwJLsGiT3x/wuOxL7x3GmCM="

addons:
  coverity_scan:
    project:
      name: "Virtual-Universe/Virtual-Universe"
      description: "Build submitted via Travis CI"
    notification_email: emperor@secondgalaxy.com
    build_command_prepend: "./runprebuild.sh -c Debug -a x64 -b Yes"
    build_command:   "xbuild"
    branch_pattern: coverity_scan

mono:
  - latest
script:
  - ./runprebuild.sh -c Debug -a x64 -b Yes
notifications:
  irc:
    channels:
      - "chat.freenode.net#galaxyfutures"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
sudo: false