var namespaceAurora_1_1Framework_1_1SceneInfo =
[
    [ "Entities", "d8/de9/namespaceAurora_1_1Framework_1_1SceneInfo_1_1Entities.html", "d8/de9/namespaceAurora_1_1Framework_1_1SceneInfo_1_1Entities" ],
    [ "AgentCircuitManager", "d9/dc3/classAurora_1_1Framework_1_1SceneInfo_1_1AgentCircuitManager.html", "d9/dc3/classAurora_1_1Framework_1_1SceneInfo_1_1AgentCircuitManager" ],
    [ "ClientManager", "d2/dcc/classAurora_1_1Framework_1_1SceneInfo_1_1ClientManager.html", "d2/dcc/classAurora_1_1Framework_1_1SceneInfo_1_1ClientManager" ],
    [ "EstateSettings", "db/d82/classAurora_1_1Framework_1_1SceneInfo_1_1EstateSettings.html", "db/d82/classAurora_1_1Framework_1_1SceneInfo_1_1EstateSettings" ],
    [ "EventManager", "db/d93/classAurora_1_1Framework_1_1SceneInfo_1_1EventManager.html", "db/d93/classAurora_1_1Framework_1_1SceneInfo_1_1EventManager" ],
    [ "IEntityCreator", "df/db2/interfaceAurora_1_1Framework_1_1SceneInfo_1_1IEntityCreator.html", "df/db2/interfaceAurora_1_1Framework_1_1SceneInfo_1_1IEntityCreator" ],
    [ "ILandObject", "d1/d36/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ILandObject.html", "d1/d36/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ILandObject" ],
    [ "IScene", "d3/d9c/interfaceAurora_1_1Framework_1_1SceneInfo_1_1IScene.html", "d3/d9c/interfaceAurora_1_1Framework_1_1SceneInfo_1_1IScene" ],
    [ "ISceneChildEntity", "d8/dc6/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneChildEntity.html", "d8/dc6/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneChildEntity" ],
    [ "ISceneGraph", "de/d17/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneGraph.html", "de/d17/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneGraph" ],
    [ "ISceneManager", "d8/d63/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneManager.html", "d8/d63/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISceneManager" ],
    [ "ISimulatorDataStore", "df/d56/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISimulatorDataStore.html", "df/d56/interfaceAurora_1_1Framework_1_1SceneInfo_1_1ISimulatorDataStore" ],
    [ "LandData", "d4/de9/classAurora_1_1Framework_1_1SceneInfo_1_1LandData.html", "d4/de9/classAurora_1_1Framework_1_1SceneInfo_1_1LandData" ],
    [ "LandUndoState", "d3/d0c/classAurora_1_1Framework_1_1SceneInfo_1_1LandUndoState.html", "d3/d0c/classAurora_1_1Framework_1_1SceneInfo_1_1LandUndoState" ],
    [ "PerlinNoise", "d3/d39/classAurora_1_1Framework_1_1SceneInfo_1_1PerlinNoise.html", "d3/d39/classAurora_1_1Framework_1_1SceneInfo_1_1PerlinNoise" ],
    [ "PrimitiveBaseShape", "d9/d9e/classAurora_1_1Framework_1_1SceneInfo_1_1PrimitiveBaseShape.html", "d9/d9e/classAurora_1_1Framework_1_1SceneInfo_1_1PrimitiveBaseShape" ],
    [ "RegionInfo", "d8/dec/classAurora_1_1Framework_1_1SceneInfo_1_1RegionInfo.html", "d8/dec/classAurora_1_1Framework_1_1SceneInfo_1_1RegionInfo" ],
    [ "RegionSettings", "d9/d05/classAurora_1_1Framework_1_1SceneInfo_1_1RegionSettings.html", "d9/d05/classAurora_1_1Framework_1_1SceneInfo_1_1RegionSettings" ],
    [ "ReturnInfo", "db/de7/structAurora_1_1Framework_1_1SceneInfo_1_1ReturnInfo.html", "db/de7/structAurora_1_1Framework_1_1SceneInfo_1_1ReturnInfo" ],
    [ "ScenePermissions", "d5/d57/classAurora_1_1Framework_1_1SceneInfo_1_1ScenePermissions.html", "d5/d57/classAurora_1_1Framework_1_1SceneInfo_1_1ScenePermissions" ],
    [ "TaskInventoryDictionary", "d1/d3c/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryDictionary.html", "d1/d3c/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryDictionary" ],
    [ "TaskInventoryItem", "df/de3/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryItem.html", "df/de3/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryItem" ],
    [ "TaskInventoryItemHelpers", "d8/d83/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryItemHelpers.html", "d8/d83/classAurora_1_1Framework_1_1SceneInfo_1_1TaskInventoryItemHelpers" ],
    [ "TerrainChannel", "dd/d5d/classAurora_1_1Framework_1_1SceneInfo_1_1TerrainChannel.html", "dd/d5d/classAurora_1_1Framework_1_1SceneInfo_1_1TerrainChannel" ],
    [ "TerrainUtil", "df/dac/classAurora_1_1Framework_1_1SceneInfo_1_1TerrainUtil.html", "df/dac/classAurora_1_1Framework_1_1SceneInfo_1_1TerrainUtil" ],
    [ "UndoState", "d5/d5e/classAurora_1_1Framework_1_1SceneInfo_1_1UndoState.html", "d5/d5e/classAurora_1_1Framework_1_1SceneInfo_1_1UndoState" ],
    [ "UuidGatherer", "d5/def/classAurora_1_1Framework_1_1SceneInfo_1_1UuidGatherer.html", "d5/def/classAurora_1_1Framework_1_1SceneInfo_1_1UuidGatherer" ]
];