var namespaces =
[
    [ "Aurora", "d2/d4d/namespaceAurora.html", "d2/d4d/namespaceAurora" ],
    [ "AvatarPreview", "dc/db3/namespaceAvatarPreview.html", "dc/db3/namespaceAvatarPreview" ],
    [ "Baker", "d5/de5/namespaceBaker.html", null ],
    [ "CSJ2K", "da/db8/namespaceCSJ2K.html", "da/db8/namespaceCSJ2K" ],
    [ "Games", "d1/d8a/namespaceGames.html", "d1/d8a/namespaceGames" ],
    [ "GridImageUpload", "d6/de6/namespaceGridImageUpload.html", "d6/de6/namespaceGridImageUpload" ],
    [ "GridProxy", "db/d60/namespaceGridProxy.html", null ],
    [ "GridProxyGUI", "d7/d25/namespaceGridProxyGUI.html", null ],
    [ "HTMLHelp", "d5/d38/namespaceHTMLHelp.html", null ],
    [ "IgeMacIntegration", "d9/d9a/namespaceIgeMacIntegration.html", null ],
    [ "ImportPrimScript", "d9/d01/namespaceImportPrimScript.html", null ],
    [ "Management", "d3/d67/namespaceManagement.html", null ],
    [ "MoneyServer", "d3/dbb/namespaceMoneyServer.html", null ],
    [ "MySQLMoneyDataWrapper", "dc/d52/namespaceMySQLMoneyDataWrapper.html", null ],
    [ "NSL", "d9/d8e/namespaceNSL.html", "d9/d8e/namespaceNSL" ],
    [ "OpenSim", "d0/d53/namespaceOpenSim.html", "d0/d53/namespaceOpenSim" ],
    [ "Prebuild", "d8/d3b/namespacePrebuild.html", "d8/d3b/namespacePrebuild" ],
    [ "RegAPI", "d8/dcc/namespaceRegAPI.html", null ],
    [ "RunTimeCompiler", "dd/d23/namespaceRunTimeCompiler.html", null ],
    [ "Simple", "d4/d56/namespaceSimple.html", "d4/d56/namespaceSimple" ],
    [ "SLImageUpload", "da/db6/namespaceSLImageUpload.html", "da/db6/namespaceSLImageUpload" ],
    [ "SmartInspect", "dd/da3/namespaceSmartInspect.html", "dd/da3/namespaceSmartInspect" ],
    [ "Stetic", "da/d31/namespaceStetic.html", null ],
    [ "Tanis", "db/d6e/namespaceTanis.html", "db/d6e/namespaceTanis" ],
    [ "WelcomePackageIARConverter", "d4/d6f/namespaceWelcomePackageIARConverter.html", null ],
    [ "WinGridProxy", "d2/d06/namespaceWinGridProxy.html", null ]
];