var namespaceAurora_1_1Services_1_1DataService =
[
    [ "Connectors", "dc/d1f/namespaceAurora_1_1Services_1_1DataService_1_1Connectors.html", "dc/d1f/namespaceAurora_1_1Services_1_1DataService_1_1Connectors" ],
    [ "GenericUtils", "d4/d3f/classAurora_1_1Services_1_1DataService_1_1GenericUtils.html", "d4/d3f/classAurora_1_1Services_1_1DataService_1_1GenericUtils" ],
    [ "LocalAbuseReportsConnector", "d1/d7a/classAurora_1_1Services_1_1DataService_1_1LocalAbuseReportsConnector.html", "d1/d7a/classAurora_1_1Services_1_1DataService_1_1LocalAbuseReportsConnector" ],
    [ "LocalAgentConnector", "d7/de4/classAurora_1_1Services_1_1DataService_1_1LocalAgentConnector.html", "d7/de4/classAurora_1_1Services_1_1DataService_1_1LocalAgentConnector" ],
    [ "LocalAssetConnector", "da/def/classAurora_1_1Services_1_1DataService_1_1LocalAssetConnector.html", "da/def/classAurora_1_1Services_1_1DataService_1_1LocalAssetConnector" ],
    [ "LocalAuthConnector", "de/d1f/classAurora_1_1Services_1_1DataService_1_1LocalAuthConnector.html", "de/d1f/classAurora_1_1Services_1_1DataService_1_1LocalAuthConnector" ],
    [ "LocalAvatarConnector", "d9/da6/classAurora_1_1Services_1_1DataService_1_1LocalAvatarConnector.html", "d9/da6/classAurora_1_1Services_1_1DataService_1_1LocalAvatarConnector" ],
    [ "LocalDataService", "d7/d03/classAurora_1_1Services_1_1DataService_1_1LocalDataService.html", "d7/d03/classAurora_1_1Services_1_1DataService_1_1LocalDataService" ],
    [ "LocalDirectoryServiceConnector", "d8/d53/classAurora_1_1Services_1_1DataService_1_1LocalDirectoryServiceConnector.html", "d8/d53/classAurora_1_1Services_1_1DataService_1_1LocalDirectoryServiceConnector" ],
    [ "LocalEmailMessagesConnector", "d2/dcc/classAurora_1_1Services_1_1DataService_1_1LocalEmailMessagesConnector.html", "d2/dcc/classAurora_1_1Services_1_1DataService_1_1LocalEmailMessagesConnector" ],
    [ "LocalEstateConnector", "db/d8d/classAurora_1_1Services_1_1DataService_1_1LocalEstateConnector.html", "db/d8d/classAurora_1_1Services_1_1DataService_1_1LocalEstateConnector" ],
    [ "LocalFriendsConnector", "dd/d3b/classAurora_1_1Services_1_1DataService_1_1LocalFriendsConnector.html", "dd/d3b/classAurora_1_1Services_1_1DataService_1_1LocalFriendsConnector" ],
    [ "LocalGenericsConnector", "da/dce/classAurora_1_1Services_1_1DataService_1_1LocalGenericsConnector.html", "da/dce/classAurora_1_1Services_1_1DataService_1_1LocalGenericsConnector" ],
    [ "LocalGridConnector", "de/df9/classAurora_1_1Services_1_1DataService_1_1LocalGridConnector.html", "de/df9/classAurora_1_1Services_1_1DataService_1_1LocalGridConnector" ],
    [ "LocalGroupsServiceConnector", "d0/d29/classAurora_1_1Services_1_1DataService_1_1LocalGroupsServiceConnector.html", "d0/d29/classAurora_1_1Services_1_1DataService_1_1LocalGroupsServiceConnector" ],
    [ "LocalInventoryConnector", "d5/ddf/classAurora_1_1Services_1_1DataService_1_1LocalInventoryConnector.html", "d5/ddf/classAurora_1_1Services_1_1DataService_1_1LocalInventoryConnector" ],
    [ "LocalMuteListConnector", "db/de8/classAurora_1_1Services_1_1DataService_1_1LocalMuteListConnector.html", "db/de8/classAurora_1_1Services_1_1DataService_1_1LocalMuteListConnector" ],
    [ "LocalOfflineMessagesConnector", "dc/dac/classAurora_1_1Services_1_1DataService_1_1LocalOfflineMessagesConnector.html", "dc/dac/classAurora_1_1Services_1_1DataService_1_1LocalOfflineMessagesConnector" ],
    [ "LocalProfileConnector", "d2/d3e/classAurora_1_1Services_1_1DataService_1_1LocalProfileConnector.html", "d2/d3e/classAurora_1_1Services_1_1DataService_1_1LocalProfileConnector" ],
    [ "LocalRegionConnector", "d7/d09/classAurora_1_1Services_1_1DataService_1_1LocalRegionConnector.html", "d7/d09/classAurora_1_1Services_1_1DataService_1_1LocalRegionConnector" ],
    [ "LocalUserAccountConnector", "dc/dbe/classAurora_1_1Services_1_1DataService_1_1LocalUserAccountConnector.html", "dc/dbe/classAurora_1_1Services_1_1DataService_1_1LocalUserAccountConnector" ],
    [ "LocalUserInfoConnector", "df/d2a/classAurora_1_1Services_1_1DataService_1_1LocalUserInfoConnector.html", "df/d2a/classAurora_1_1Services_1_1DataService_1_1LocalUserInfoConnector" ],
    [ "LocalUserStatsDataConnector", "d3/d70/classAurora_1_1Services_1_1DataService_1_1LocalUserStatsDataConnector.html", "d3/d70/classAurora_1_1Services_1_1DataService_1_1LocalUserStatsDataConnector" ]
];