var namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine =
[
    [ "APIs", "d7/d59/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1APIs.html", "d7/d59/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1APIs" ],
    [ "CompilerTools", "d0/dc5/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1CompilerTools.html", "d0/dc5/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1CompilerTools" ],
    [ "MiniModule", "dc/d22/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MiniModule.html", "dc/d22/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MiniModule" ],
    [ "Plugins", "d5/d2d/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1Plugins.html", "d5/d2d/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1Plugins" ],
    [ "Runtime", "da/d47/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1Runtime.html", "da/d47/namespaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1Runtime" ],
    [ "AppDomainManager", "db/dfe/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1AppDomainManager.html", "db/dfe/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1AppDomainManager" ],
    [ "AssemblyResolver", "d4/dab/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1AssemblyResolver.html", "d4/dab/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1AssemblyResolver" ],
    [ "DetectParams", "d4/dcd/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1DetectParams.html", "d4/dcd/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1DetectParams" ],
    [ "EnumeratorInfo", "d4/d6c/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EnumeratorInfo.html", "d4/d6c/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EnumeratorInfo" ],
    [ "EventAbortException", "d7/dd0/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventAbortException.html", "d7/dd0/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventAbortException" ],
    [ "EventInfo", "da/d3d/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventInfo.html", "da/d3d/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventInfo" ],
    [ "EventManager", "da/d3d/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventManager.html", "da/d3d/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventManager" ],
    [ "EventParams", "d5/dff/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventParams.html", "d5/dff/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1EventParams" ],
    [ "IScript", "d2/d5f/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScript.html", "d2/d5f/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScript" ],
    [ "IScriptApi", "d6/d3b/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptApi.html", "d6/d3b/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptApi" ],
    [ "IScriptModulePlugin", "de/d8b/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptModulePlugin.html", "de/d8b/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptModulePlugin" ],
    [ "IScriptPlugin", "d1/dbc/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptPlugin.html", "d1/dbc/interfaceAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1IScriptPlugin" ],
    [ "LSL_Types", "dc/dba/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1LSL__Types.html", "dc/dba/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1LSL__Types" ],
    [ "LUStruct", "d1/d02/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1LUStruct.html", "d1/d02/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1LUStruct" ],
    [ "MaintenanceThread", "d4/dc1/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MaintenanceThread.html", "d4/dc1/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MaintenanceThread" ],
    [ "MinEventDelayException", "d8/da7/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MinEventDelayException.html", "d8/da7/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1MinEventDelayException" ],
    [ "QueueItemStruct", "d5/d54/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1QueueItemStruct.html", "d5/d54/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1QueueItemStruct" ],
    [ "ScriptData", "d7/dbf/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptData.html", "d7/dbf/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptData" ],
    [ "ScriptDeleteException", "d0/d92/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptDeleteException.html", "d0/d92/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptDeleteException" ],
    [ "ScriptEngine", "dc/d97/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptEngine.html", "dc/d97/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptEngine" ],
    [ "ScriptErrorReporter", "dd/d8b/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptErrorReporter.html", "dd/d8b/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptErrorReporter" ],
    [ "ScriptEventsProcData", "db/d00/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptEventsProcData.html", "db/d00/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptEventsProcData" ],
    [ "ScriptPermissionsException", "d5/ddd/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptPermissionsException.html", "d5/ddd/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptPermissionsException" ],
    [ "ScriptProtectionModule", "d7/d12/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptProtectionModule.html", "d7/d12/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptProtectionModule" ],
    [ "ScriptStateSave", "d4/d0f/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptStateSave.html", "d4/d0f/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1ScriptStateSave" ],
    [ "SelfDeleteException", "d2/d32/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1SelfDeleteException.html", "d2/d32/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1SelfDeleteException" ],
    [ "StartPerformanceQueue", "d1/db9/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1StartPerformanceQueue.html", "d1/db9/classAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1StartPerformanceQueue" ],
    [ "StateQueueItem", "d4/d5b/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1StateQueueItem.html", "d4/d5b/structAurora_1_1ScriptEngine_1_1AuroraDotNetEngine_1_1StateQueueItem" ]
];